_commit: fe21eee73f47a659640e02590a3d72ca82f2ca35
_src_path: cookiecutter-monarch-ingest
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: An automated ingest transforming the upheno data artifact upheno-cross-species.sssom.tsv into KGX.
project_name: upheno-cross-species-ingest
project_slug: upheno_cross_species_ingest
